### ISSUE TITLE
Win10 Improvement: Use WaitForDebugEventEx instead of WaitForDebugEvent

### ISSUE THREAD

**Issue by Nukem9** [x64dbg/GleeBug#41]
Taken from https://github.com/x64dbg/x64dbg/issues/388
 
---
WaitForDebugEventEx

https://msdn.microsoft.com/en-us/library/windows/desktop/mt171594(v=vs.85).aspx

**Comment by mrexodia** [comment]
could anybody with windows 10 test if these are actually different functions and not that `WaitForDebugEvent` forwards to `WaitForDebugEventEx`? I don't see any difference in their prototype or data structures.

**Comment by Nukem9** [comment]
![image](https://cloud.githubusercontent.com/assets/4228359/12248361/e313d210-b886-11e5-93bc-325e5e65e1aa.png)

Top: `WaitForDebugEvent`
Bottom: `WaitForDebugEventEx`

**Comment by mrexodia** [comment]
Okay they do some ugly internal function with a bool for unicode. Pushing a
fix
